#!/bin/bash

#source .env

mkdir -p build
./compiler/compiler pages/index.html templates.html > build/index.html

mkdir -p build/files
cp -r files/ build/
tailwindcss --input main.css --output build/files/styles.css

